//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class tenantspage
    {
        public int PageId { get; set; }
        public string PageName { get; set; }
        public int TenantId { get; set; }
        public int PageType { get; set; }
        public string PhysicalFileName { get; set; }
        public string FileContent { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public int CreateUserID { get; set; }
        public string LayoutitContent { get; set; }
    }
}
